INSERT INTO stories (owner_id, title, content, is_complete, photo_url, created_at, storyurl_id)
VALUES 
(1, 'In Nature', 'A week before Christmas, Maggie’s son is married in the bare spot of land under the hemlocks where nothing ever grows. Maggie hangs white lights in the branches. She covers her son’s pregnant bride in a pale woolen blanket. She wakes early the morning of the wedding and spends hours digging a path through the fresh snow so that the guests—the bride’s aunt, and friends from the ranch where the young couple works—can come up to her cabin for warm bread and jam and champagne. At some point, glitter is thrown. Weeks later, when the snow melts in patches, Maggie finds it mixing into the earth and curses.

All throughout January Maggie is awoken by the foxes’ tortured mating calls, like children’s screams, breaking through the night. She sleeps terribly, but there’s comfort in the foxes’ ancestral routines. The country is a lonely and strange place. Her husband has been dead for years. Her child is an adult. There are people, in other houses, through the woods, but in the ten years she’s lived here, no one has ever invited her for dinner. She finds herself eager for cub season, when the foxes return to the den under her tool shed.

That day arrives in the first week of March, on a morning when the cold still blows its way through the trees. Inside, Maggie grows seedlings under hot little lamps. She reads a library book about birdsongs. She brews tea; she drinks vats of it. Maggie’s son calls and tells her he is coming home.

On the phone everything is already decided. He has packed and closed the door on his life at the ranch. The girl will go back to her aunt’s; she’ll have the baby there. Just like that, the newlyweds will split and be absorbed into the old families, the way the snowy woods make animals appear and then swallow them up again.

Maggie loves her son. She should be grateful for the company. But she always thought that one day he would just be grown; done, like something in an oven.

At first he is eager. He chops firewood, makes trips into town. He poisons a colony of ants that have been nesting in the roof for too long. He treats Maggie like she’s much older than she is, like she wasn’t able to do these things without him around.

At night they eat stew, and he catches her up on news she’s missed from the outside world. She listens to him talk in circles; there’s an edge to his politics that she doesn’t remember. His hair is long, his palms are callused. Maggie doesn’t know why he was asked to leave the ranch. She knows the place, the type of people it hires and lets return year after year, the things it sweeps under rugs. Perhaps it’s better not to ask.

He looks for work. One day he lopes to the edge of the road and catches a ride to the big town, an hour away. When Maggie cleans his room, she gathers new information about him, strange talismans. Wild mushrooms in a neat row on his dresser. A long gray hair on his pillow. A torn piece of newspaper advertising a vacant tavern by the state line. A dark form under the bed she reaches for, then changes her mind. Her son returns after midnight and is sullen for days. She could fill a well with the things she doesn’t know.

Maggie waits for a few warm days in a row and then turns the earth to plant her seedlings. The dog fox watches from the edge of the woods. With a new litter he hunts for the whole family. He’s been known to go through the neighbor’s trash, to tear up her garden. His responsibility makes him rash and desperate. But foxes parent for one fierce, sweet season and then release. By June the cubs will be off to their own territories.

When there’s nothing else to do Maggie walks for hours through the woods. She catalogs changes: the new growth, the dead trees that have fallen or are about to fall. She has always been a quick study. Once she worked in a museum. Once she lived in a big city. Then she started tunneling out to quieter places, searching for her own home, anything different from the sterile, colorless suburbs where she was raised. Now she can’t remember what had really been so bad about them.

After the last frost she lets the chickens out into their yard. It’s a pen full of sunlight, reinforced by double wiring. The dog fox sulks. She can almost see him licking his lips. Her son joins her on the porch and together they watch the animal retreat into the woods.

At the ranch we take them out with a twenty-two, her son boasts, disappearing into the house, but he returns with a gun much bigger than that. It fits so easily against him. Maggie catches her breath; she feels weightless, suddenly, and has to steady herself on the railing. She watches her son cock and point the loaded weapon into the woods at a spot of nothing. The fox is long gone.

Then she turns towards the trees and shakes her head slowly. That’s not how I take care of things, she says to him. But when she looks back, he is already inside.

Sometimes Maggie just wants to give in and let the foxes take what they need. Humans have so much, so easily. She pictures her son as a boy, pulling down colorful boxes in the sugary cereal aisle. She sees his small, angry body, its clammy desperation when she would hold him back from a tantrum. So much in nature, she thinks, can be boiled down to hunger. But human hunger is a bigger, more frightening thing. She remembers the other child, the new one; she counts the months in her head until there are nine.

In her sleep that night, Maggie is visited by the parties of her youth. The lights, the strangers, the buzzing. When she wakes to a dirty kitchen, she is still fondly inside of her dream. A bottle of champagne, left over from the wedding, knocks softly against her feet. Cooking wine, a can of stout lying in its own thick brown spit. It’s like the house has been sucked dry of everything. She finds her son asleep by the door. He’s so much heavier than the last time she ever carried him. Still, she drags him out onto the porch. Then she takes his bags, his sweaters, his books, and puts them in a pile by the edge of the woods. She covers his passed-out body in a loose woolen throw. Then she goes for a long walk.

The days are so long now; the light in late evening is breathtaking. Her garden does well that year. Her chickens give far more eggs than one person could eat. She leaves them in baskets on the neighbors’ porches, with notes that Maggie hopes sound friendly. One morning she bakes a cake and eats the entire thing before noon. Then she bakes another. She’s missed this side of solitude, its boundarylessness. For months she’ll look out at the blank spot under the hemlocks, and think: Once there was a boy, who now has disappeared.', FALSE, 'https://images.pexels.com/photos/247399/pexels-photo-247399.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', '2020-8-25 12:15:01', '9fa2Wf'),
(1,'Fish Jokes', '>°))))><<
To start, Anna searches for his name. The search returns 5,881 emails—every single thing he sent her for the thirteen months they worked together. She filters out his work address but his personal Gmail still returns 1,739. Too many to comb through one by one. She can’t search by date; she doesn’t remember the date. If she’s going to find this email, she’s going to have to remember the words he used.

She tries “sexy.” But she forgets to type “sexy AND” his name, so the search returns every time anyone has ever emailed her the word “sexy” (476 times). When she ANDs his name, the search returns zero; apparently her old boss never used the word “sexy.”

Anna doesn’t remember the exact words he used in the email, but the word “sexy” should have been prominent. Its absence makes her nervous.

She tries “baby” and “beautiful.” It was something like that. Something she can forward to her friend Travis, who’s considering her old boss for a job and wants to know what Anna thinks of him. Anna doesn’t want to explain. She wants to forward Travis the email, which will explain everything.

She tries “sweetheart” and “honey.” She remembers there was some word like that early in the email—the salutation, or the first line—that startled her, and she had deleted the email abruptly, like throwing her shoe at a mouse. The email was obvious. (Although it wasn’t enough to get him fired at the time. She knew what happened if you got your boss fired like that.) Later that night, she got out of bed and undeleted it. Later still, she exported her entire work email archive, in case she needed a paper trail. But neither “sweetheart” nor “honey” finds the one.

She tries “alluring” and “gorgeous,” even though they sound fake. What do men actually say? She can only think of clichés. She tries “even though I’m married” and “I know it’s wrong” and “my wife” with no luck.

His email was a cliché, but there was no cliché for her response. When the email first arrived, Anna had no idea what to do; she’d taken her laptop into the glassed-in conference room and hid for hours. The end panel of the glass wall had been cracked (some previous tenant’s drama) and replaced with beige MDF. She sat on the floor with her back to that panel and watched, hiding, as everyone left the office but him. When the cleaning staff turned out the lights, she made a dash for it. The lobby was dark, the tropical fish tank washing the room in electric blue. She imagined him sitting in his office, listening for her, and pushed the elevator button a bunch of times as if she could make it speed up. Later she realized he was working from home that day. She searches for “thinking of you” and “dreaming of you” and gets nothing.

They used a cliché when they fired her a few months later: “restructuring.” And another one a few months after that—“pivoting”—when the entire company shut down. She was fluent in all of those clichés; she laughed out loud when she heard the news about the “pivot.” By then she had a new title, a higher salary. She was glad she had kept quiet and kept her reputation intact.', FALSE, 'https://images.pexels.com/photos/952594/pexels-photo-952594.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', '2020-01-05 00:01:01', 'A7A9O1'),
(3, 'Mrs. Bad Dream', 'When my brother and I got home from school one afternoon, there was a round little woman sitting at the kitchen counter in our apartment. She was reading a paperback, drinking an orange soda, guarding a purse as big as an overnight bag in her lap. She looked as if she’d wandered in, as if she thought the bus stopped there. We stood in the doorway and watched her, until finally she glanced up and announced in a high, sweet voice that she was Mrs. Bad Dream, that she’d stay until our father got home with dinner, and that she hoped he wouldn’t be late, because Mr. Bad Dream was expecting her. Then she went back to her book. My brother, who was in the seventh grade and didn’t see the point of babysitters, went off to our bedroom. I sat alone on the couch in the living room. With her perched just a few feet behind me, I didn’t feel like watching TV. And I had a policy against doing homework before dinner. That left talking to the babysitter. Babysitters always wanted to talk; maybe they were sorry for us. My brother hated the talking—and the pity—but I didn’t mind. I turned and asked her what her book was about.

“It’s about a famous tree,” she said, not looking up. “In New Hampshire.”

“We had a pawpaw tree in the backyard at our old house,” I said. “My mom would make jam. I didn’t really like it, though.” She had no reply to that, so I let her read.

When our father got home—on time—Mrs. Bad Dream put her book in her purse, climbed off the stool, told him we’d been perfect angels, and went home to Mr. Bad Dream.',FALSE,'https://images.pexels.com/photos/1930009/pexels-photo-1930009.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500','2019-08-09 03:10:05','98EDPO'),
(1, 'Upon the Mountainside', 'Lyncon entered the village with his sword drawn, baring the blue-grey blade. The village was deathly quiet, not a creature stirred while even the wind seemed absent, instead the air feeling heavy with foreboding. Lyncon moved cautiously forward, treading lightly while his eye flitted from one spot to the next. Beside him, Vanhelm sensed it too and sniffed the air, his tail stilled.', FALSE, 'https://images.pexels.com/photos/2574643/pexels-photo-2574643.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', '2019-05-19 03:10:05', '8ASCWE'),
(4, '5 Questions for the Snake Charmer','At some point on my way to the nephew’s birthday without a present, somewhere between swigging Gatorade and weaving around piss puddles and clamping my lips against vomit or provocative statements (as my dear sister puts it), I feel a hand grab mine. A shock of warmth, then the hard shove of a box.

I watch enough news to know: I’m holding a bomb. In a few seconds the wet red jelly of me, still smelling of last night’s mint and Campari, will scatter the city streets like confetti.

I wait for emotion to fill me. All that emerges is an acid burp. My heartbeat persists and I realize that this waiting (Therapy Intake Form, Question 1. Are you prone to disastrous thoughts?) has gone on for more than a few seconds. I realize the pedestrians swerving around me are shooting dirty looks. I realize I remain disappointingly unchanged: hungover, dehydrated, inconvenient, unexploded. I realize that half a block ago I dropped a five on the blanket of a homeless man who sat surrounded by piles of gray boxes like this one. Sagging boxes whose sad color tickled chemicals in my blood, fired neurons that caused me to open my wallet. The man wasn’t homeless (Question 2. Do you project disaster onto people around you?) but an entrepreneur. I flip the box over. On its bottom side, in painstakingly hand-lettered Sharpie:

YOUR OWN PERFECT WORLD!!! SAFE FOR CHILDREN!!!

1 LOCALLY SOURCED GROW-YOUR-OWN ANT FARM

*

You’re not truly late to a party if there’s cake left. Buttercream mixes violently with the last of the booze in my stomach as I watch the nephew upend his box.', FALSE, 'https://images.pexels.com/photos/4096517/pexels-photo-4096517.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500','2017-12-13 14:12:01', 'J2UQ1X');