INSERT INTO contributions (user_id, story_id, content, accepted, created_at)
VALUES 
(3, 1, 'When there’s nothing else to do Maggie walks for hours through the woods. She catalogs changes: the new growth, the dead trees that have fallen or are about to fall. She has always been a quick study. Once she worked in a museum. Once she lived in a big city. Then she started tunneling out to quieter places, searching for her own home, anything different from the sterile, colorless suburbs where she was raised. Now she can’t remember what had really been so bad about them.', FALSE, '2020-07-30'),
(6, 1, 'Sometimes Maggie just wants to give in and let the foxes take what they need. Humans have so much, so easily. She pictures her son as a boy, pulling down colorful boxes in the sugary cereal aisle. She sees his small, angry body, its clammy desperation when she would hold him back from a tantrum. So much in nature, she thinks, can be boiled down to hunger. But human hunger is a bigger, more frightening thing. She remembers the other child, the new one; she counts the months in her head until there are nine.', FALSE, '2020-07-25'),
(2, 1, 'In her sleep that night, Maggie is visited by the parties of her youth. The lights, the strangers, the buzzing. When she wakes to a dirty kitchen, she is still fondly inside of her dream. A bottle of champagne, left over from the wedding, knocks softly against her feet. Cooking wine, a can of stout lying in its own thick brown spit. It’s like the house has been sucked dry of everything. She finds her son asleep by the door. He’s so much heavier than the last time she ever carried him. Still, she drags him out onto the porch. Then she takes his bags, his sweaters, his books, and puts them in a pile by the edge of the woods. She covers his passed-out body in a loose woolen throw. Then she goes for a long walk.', FALSE, '2020-06-25'),
(5, 2, 'And now here she is. Three years later, and her friend Travis wants her advice about whether or not to hire her old boss—who was not “infatuated with” or “attracted to” her, who did not have a “crush,” but who had (or who was) something like that.', FALSE, '2020-07-05'),
(4, 2, 'The boss had insisted on that something for a month. Never again over email; he caught her in sandwich shops, caught her wrist in the hall, and kept talking to her in a low voice about that something until her polite reluctance offended him and he took everything he’d ever said to her back, with interest. She had never become so disposable so suddenly. The rapid change had disoriented her. She tried not to miss the attention. She used to catch herself in meetings, seeking his eye. She tries “enraptured” and “entrapped” with no luck.', FALSE, '2020-07-05'),
(4, 2, 'She’s not too proud to use a thesaurus. “Alluring” and “appealing” and “charming.” “Fascinating” and “gorgeous” and “pleasing.” She tries “love,” although she knows that’s not what the email was about. “Love” turns up 653 emails. He did love that job. Anna loved that job, too. None of his “love” emails make any sense. One of them says: “hey guys hers one I rly rly love.”', FALSE, '2020-07-05'),
(1, 5, 'He stood up and stared across the river and pondered if he should cross.', FALSE, '2020-07-05'),
(1, 3, 'I didn’t know if Mrs. Bad Dream would agree. Maybe she enjoyed reading about Russian history and chess. But when we got home there was another babysitter waiting for us, a younger one with long straight hair, big round glasses, and big round earrings. She said she was thrilled to meet us and she was sure we’d get along if we all followed some simple ground rules. My brother and I agreed that she was hateful. It was good to agree about something for once. She was the last babysitter we had; six months later she and my father got married.', FALSE, '2020-06-23'),
(2, 3, 'When it was clear Mrs. Bad Dream wasn’t coming back, I asked my father where she lived, so I could return the book.', FALSE, '2020-07-28'),
(3, 4, 'And later, movement from the master bedroom that might be the makings of another nephew, movement of corks from new bottles and wine into a mug I quietly fill because who wants to hear that? Who wants a soundtrack to their own alone-ness?', TRUE, '2020-07-28');
